name: 02 - evento issue
on: 
    push:
    issues:
        types:
            - opend
jobs:
    hola-mundo:
         runs-on: ubuntu-latest
         steps:
         - name: Hola mundo
         run: echo "¡Hola mundo!"
